
name: Java CI
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up JDK 17
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -Drevision=${{github.ref_name}}  --batch-mode --update-snapshots verify

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@f748a0599171a192a2668afee8d0497f7c1069df

      - name: Upload artifacts to JFrog
        run: |
           mkdir ${{ github.ref_name }}
           cp target/*.jar ${{ github.ref_name }}/.
           jfrog rt u "${{ github.ref_name }}/*.jar" akeyless-java/io/akeyless/cloudid-lightweight/ --url=https://akeyless.jfrog.io/artifactory --user=ci-user --password=${{ secrets.ARTIFACTORY_ACCESS_KEY }}
           sed "s/\${revision}/${{ github.ref_name }}/g" pom.xml > target/cloudid-lightweight-${{ github.ref_name }}.pom
           cp target/*.pom ${{ github.ref_name }}/.
           jfrog rt u "${{ github.ref_name }}/*.pom" akeyless-java/io/akeyless/cloudid-lightweight/ --url=https://akeyless.jfrog.io/artifactory --user=ci-user --password=${{ secrets.ARTIFACTORY_ACCESS_KEY }}
